<?php

namespace App\Http\Requests;


class StoreSubscriptionRequest extends MainRequest
{
    public function rules(): array
    {
        return [
            'mail_address'=>['required','string'],
            'status'=>['nullable','boolean'],
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
