<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UserRequest extends MainRequest
{
    public function rules(): array
    {
        return [
            'name' => 'required | string',
            'email' => 'required | string',
            'password' => 'required | string'
        ];
    }
    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
